all_train_cfgs = {
    'v8n': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '2',
        'workers': 8,
        'seed': 0,
    },

    'v8n-spd': {
        'model_name': 'yolov8n-spd.yaml',
        'name': 'endovis-v8n-spd-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '2',
        'workers': 8,
        'seed': 42,
    },

    'v8n-mu': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-mu',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '3',
        'workers': 8,
        'mixup': 0.5,
        'use_mixupplus': False,
        'seed': 0,
    },

    'v8n-rmt1-p1': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt1-p1-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '0',
        'workers': 8,
        'rmt': 0.1,
        'rmt_type': 1,
        'seed': 42,
    },

    'v8n-rmt1-p2': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt1-p2-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '1',
        'workers': 8,
        'rmt': 0.2,
        'rmt_type': 1,
        'seed': 42,
    },

    'v8n-rmt1-p5': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt1-p5-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '1',
        'workers': 8,
        'rmt': 0.5,
        'rmt_type': 1,
        'seed': 42,
    },

    'v8n-rmt2-p1': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt2-p1-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '2',
        'workers': 8,
        'rmt': 0.1,
        'rmt_type': 2,
        'seed': 42,
    },

    'v8n-rmt2-p2': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt2-p2-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '3',
        'workers': 8,
        'rmt': 0.2,
        'rmt_type': 2,
        'seed': 42,
    },

    'v8n-rmt2-p5': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt2-p5-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '0',
        'workers': 8,
        'rmt': 0.5,
        'rmt_type': 2,
        'seed': 42,
    },

    'v8n-rmt3-p1': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt3-p1-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '0',
        'workers': 8,
        'rmt': 0.1,
        'rmt_type': 3,
        'seed': 42,
    },

    'v8n-rmt3-p2': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt3-p2-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '2',
        'workers': 8,
        'rmt': 0.2,
        'rmt_type': 3,
        'seed': 42,
    },

    'v8n-rmt3-p5': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-rmt3-p5-42',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '3',
        'workers': 8,
        'rmt': 0.5,
        'rmt_type': 3,
        'seed': 42,
    },

    'v8n-cf-p1': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-cf-p1',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '0',
        'workers': 8,
        'cutoff': 0.1,
        'seed': 0,
        'optimizer': 'AdamW',
        'lr0': 1e-3
    },

    'v8n-cf-p2': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-cf-p2',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '2',
        'workers': 8,
        'cutoff': 0.2,
        'seed': 0,
    },

    'v8n-cf-p5': {
        'model_name': 'yolov8n.pt',
        'name': 'endovis-v8n-cf-p5',
        'data': 'datasets/endovis.yaml',
        'epochs': 300,
        'device': '3',
        'workers': 8,
        'cutoff': 0.5,
        'seed': 0,
    },

}